### PR TITLE
Projects backend

### PR DESCRIPTION
**Pull request by kaycbas**
Setup fetchProjects & fetchUserProjects to grab users slice also (still working on other projects routes)

### CODE REVIEW

**Review by nverno — APPROVED** [review]
looks good

**Comment by nverno** [comment]
Should fetching a project populate the comments for that project as well?

**Comment by nverno** [comment]
Once the GET '/users/:userId' route populates projects for a user, the GET '/projects/user/:userId' may be redundant

**Comment by kaycbas** [comment]
@nverno Yeah, that is a bit redundant. I'll leave it in and if it never gets used I can clean it up.

And good call - I'll make projects also fetch associated comments.

**Pull request merged**
